trassir/conan-center-index

.github/workflows/zlib.yml, .gitignore, build.py
Checks if it is buildable for any pull request which affects the library's files.
Builds and uploads to https://bintray.com/beta/#/trassir/conan-public on any push to trassir-ci branch which affects the library's files.
=> T6483: CI/CD for zlib 1.2.11 library

.github/workflows/zlib-1.2.11.yml
=> rename zlib workflow

.github/workflows/jsoncpp.yml, .github/workflows/zlib-1.2.11.yml, .github/workflows/zlib.yml, build.py
see conan-io/conan-package-tools/issues/479
=> workaround for cpt username channel behavior

.github/workflows/openssl.yml
=> add openssl 1.0.2r requiered by grpc 1.20 to build list

.github/workflows/jsoncpp.yml, .github/workflows/libalsa.yml, .github/workflows/openssl.yml, .github/workflows/zlib-1.2.11.yml, build.py
- Requires https://github.com/trassir/run-cpt/pull/10 for checks to pass
- Relies on changes in CPT package from https://github.com/trassir/conan-package-tools/compare/develop...trassir:fix-479-trassir?expand=1#diff-260d972516d64dfcd8846b0d008e6116 (see also https://github.com/conan-io/conan-package-tools/pull/482 and https://github.com/conan-io/conan-package-tools/pull/483)
=> Use forked CPT with username/channel fixes

.github/workflows/c-ares.yml
=> add action for building c-ares

.github/workflows/zlib-1.2.11.yml
=> Make zlib job name follow our converntions

.github/workflows/yasm.yml
=> add yasm CI

.github/workflows/c-ares.yml
=> add c-ares 1.14.0 to build list

.github/workflows/protobuf-3.9.x.yml
=> add gcc9 to compilers list for protobuf

.github/workflows/protoc-3.9.1.yml, recipes/protoc/3.9.1/conanfile.py
=> use compiler and arch in package_id generation for protoc

.github/workflows/etcd-grpc.yml, recipes/etcd-grpc/all/conandata.yml, recipes/etcd-grpc/all/conanfile.py, recipes/etcd-grpc/config.yml
=> add etcd-grpc

.github/workflows/libiconv.yml
=> add libiconv CI

.github/workflows/sqlite3.yml
=> add sqlite3 CI

.github/workflows/libuuid.yml
=> add libuuid CI

.github/workflows/expat.yml
=> add expat CI

.github/workflows/freetype.yml
=> add freetype CI

.github/workflows/fontconfig.yml, recipes/fontconfig/all/LICENSE, recipes/fontconfig/all/README.md, recipes/fontconfig/all/conanfile.py, recipes/fontconfig/all/forked-from.txt, recipes/fontconfig/all/test_package/CMakeLists.txt, recipes/fontconfig/all/test_package/conanfile.py, recipes/fontconfig/all/test_package/example.c, recipes/fontconfig/config.yml
=> add fontconfig CI

.github/workflows/odbc.yml
=> add odbc CI

.github/workflows/libelf.yml
=> Add libelf CI

.github/workflows/sqlite3.yml
=> update to version 3.31.0

.github/workflows/zlib-1.2.11.yml
=> build with gcc8

.github/workflows/x11.yml, recipes/x11/all/x11.json
=> add xkeyboard-config

.github/workflows/x11.yml, recipes/x11/all/x11.json
=> add libpciaccess

.github/workflows/libdrm-2.4.100.yml, recipes/libdrm/2.4.100/CMakeLists.txt, recipes/libdrm/2.4.100/conandata.yml, recipes/libdrm/2.4.100/conanfile.py, recipes/libdrm/2.4.100/test_package/CMakeLists.txt, recipes/libdrm/2.4.100/test_package/conanfile.py, recipes/libdrm/2.4.100/test_package/test_package.cpp, recipes/libdrm/forked-from.txt
=> add libdrm

.github/workflows/x11.yml, recipes/x11/all/x11.json
=> add libxext

.github/workflows/libwebp.yml
=> add libwebp

.github/workflows/libxml2.yml
=> add libxml2

.github/workflows/libjpeg-turbo.yml
=> add libjpeg-turbo

.github/workflows/libalsa.yml
=> build libalsa with gcc8

.github/workflows/openal.yml
=> build openal with gcc8

.github/workflows/axtls-1.5.3.yml
=> build axtls with gcc8

.github/workflows/xkbcommon.yml
=> use old-style apt command for ubuntu 12 compatibility

.github/workflows/x11.yml
=> use custom docker image for building x11 libs

.github/workflows/x11.yml, recipes/x11/all/x11.json
=> add libxdamage

.github/workflows/x11.yml, recipes/x11/all/x11.json
=> add some x11 libs

.github/workflows/libelf.yml
=> build libelf with gcc8

.github/workflows/ninja.yml
=> add ninja CI

.github/workflows/ninja.yml
=> build ninja on macos

.github/workflows/expat.yml
=> build expat in new docker

.github/workflows/qtwebkit-5.212.0-alpha4.yml, recipes/qtwebkit/5.212.0-alpha4/clang-11-jsc.patch, recipes/qtwebkit/5.212.0-alpha4/conanfile.py
=> add qtwebkit

.github/workflows/mesa.yml, recipes/mesa/all/conanfile.py
=> build mesa for linux

.github/workflows/sqlite3.yml
=> build sqlite3 with custom docker

recipes/xkbcommon/all/conanfile.py
=> add xcb-xkb to package_info in xkbcommon

.github/workflows/xkbcommon.yml
=> build xkbcommon with custom docker

.github/workflows/double-conversion.yml, .github/workflows/mesa.yml, .github/workflows/openh264.yml
=> compile with enabled -std=c++11 flag (for qt5 build)

.github/workflows/libjpeg-turbo.yml, .github/workflows/libwebp.yml, .github/workflows/libxslt_1.1.33.yml, recipes/libxslt/1.1.33/test_package/CMakeLists.txt
=> build qtwebkit deps with custom docker

recipes/qtwebkit/5.212.0-alpha4/conanfile.py
=> synchronize qt options with conanfile

.github/workflows/openssl.yml
=> add openssl 1.0.2r for grpc build

.github/workflows/c-ares.yml, .github/workflows/protobuf-3.9.x.yml
=> build grpc deps in custom docker

.github/workflows/grpc-1.20.0.yml, recipes/grpc/1.20.0/conanfile.py, recipes/grpc/1.20.0/patches/18729.patch, recipes/grpc/1.20.0/patches/gettid.patch, recipes/grpc/1.20.0/patches/grpc.patch
=> build grpc with custom docker

.github/workflows/qt-5.14.1.yml, recipes/qt/5.14.1/conanfile.py
=> add linux to build list

.github/workflows/etcd-grpc.yml
=> build etcd-grpc with custom docker

.github/workflows/qt-5.14.1.yml
=> build qt with openssl

recipes/etcd-grpc/all/conanfile.py
=> update grpc version to 1.26.0

.github/workflows/x11.yml, recipes/x11/all/x11.json
=> add libxcomposite

.github/workflows/libcurl.yml
=> build with custom docker

build.py
=> Set config url for Win and Mac

.github/workflows/qt-5.14.1.yml
В новом `conan-gcc8` симлинк на g++ уже выставлен
=> update qt yaml for latest docker image

.github/workflows/boost.yml, .github/workflows/ffmpeg-3.3.1.yml
=> Update xcode version to 11.4

.github/workflows/gperf.yml
=> Add gperf CI

recipes/fontconfig/all/conanfile.py
=> fontconfig: use gperf instead of gperf_installer

.github/workflows/ffmpeg-3.3.1.yml
@mm0d  утверждает, что в старом чруте ffmpeg был собран без  vdpau
=> build ffmpeg without pulseaudio and vdpau

recipes/x11/all/conanfile_base.py, recipes/x11/all/manage.py, recipes/x11/all/patches/xcb-util-image.patch, recipes/x11/all/x11.json
=> build x11 shared libs

.github/workflows/libunwind.yml
=> add libunwind yml

.github/workflows/libunwind.yml
=> dont build libunwind on mac

.github/workflows/openal.yml
сборка openal нужна и для линукса
=> openal: add linux to build os list

.github/workflows/ffmpeg-3.3.1.yml, recipes/ffmpeg/3.3.1/conanfile.py
=> ffmpeg: use libva from conan instead of system

.github/workflows/libusb.yml
=> add libusb CI

recipes/qtwebkit/5.212.0-alpha4/conanfile.py
C icu 64.2 на линуксе все падает
=> qtwebkit: use older version of icu

.github/workflows/libffi.yml
=> add github action

recipes/icu/all/conanfile.py
Изменено значение параметра with-data-packaging согласно http://userguide.icu-project.org/icudata
=> icu: change data packaging type

.github/workflows/glib.yml, recipes/glib/all/LICENSE.md, recipes/glib/all/conandata.yml, recipes/glib/all/conanfile.py, recipes/glib/all/forked-from.txt, recipes/glib/all/test_package/CMakeLists.txt, recipes/glib/all/test_package/conanfile.py, recipes/glib/all/test_package/test_package.cpp, recipes/glib/config.yml
glib нужен для сборки gstreamer
=> add glib CI

.github/workflows/zlib-1.2.11.yml
=> T10781: zlib CI on Windows OS

.github/workflows/strawberryperl-5.30.0.1.yml
It is a requirement for openssl on Windows.
Strawberryperl's recipe is for Windows only.
=> T10782: Strawberryperl CI

.github/workflows/nasm.yml
This is a requirement for openssl.
=> T10782: nasm CI for Windows

.github/workflows/zlib-1.2.11.yml
=> T10781: zlib CI for Windows, 32-bit

.github/workflows/yasm.yml
Случайно удалил yasm, когда для винды его делал.
Похоже, никак иначе его не восстановить.
=> Rebuild  yasm for linux/macos

.github/workflows/xz_utils.yml
Исправил yaml файл для дебаг-сборки, которая не была собрана из-за отсутствия указания на архитектуру.
=> T11045: xz_utils for win32, vc2019, debug build

.github/workflows/jsoncpp.yml, recipes/jsoncpp/all/test_package/conanfile.py
=> jsoncpp/1.8.3 on Windows

builder/environment.py
=> update according to trassir/conan-config/pull/11

trassir/win32-vc16/conanfile.txt
=> T12954: c-ares for win

builder/build.py
=> do not force upload

recipes/boost/all/conandata.yml, recipes/boost/all/patches/DSSL_JIRA_GRAB3032.patch, trassir/lnvr-gcc8/conanfile.txt, trassir/win32-vc16/conanfile.txt
=> T11044: use boost/1.69.0 for win32-vc16

trassir/win32-vc16/conanfile.txt
=> T13849: openal/1.20.1 for win32-vc16

.github/workflows/build.yml, builder/environment.py
=> T13607: Научить сборки conan на GHA работать с Artifactory

trassir/win32-vc16/conanfile.txt
=> T13190: conan package - opencv/2.4.13.5 for windows

recipes/leveldb/all/CMakeLists.txt, recipes/leveldb/all/conandata.yml, recipes/leveldb/all/conanfile.py, recipes/leveldb/all/test_package/CMakeLists.txt, recipes/leveldb/all/test_package/conanfile.py, recipes/leveldb/all/test_package/test_package.cpp, recipes/leveldb/config.yml, recipes/leveldb/forked-from.txt, trassir/win32-vc16/conanfile.txt
Specify library name and version:  **leveldb/1.22**
=> T14024: conan package - leveldb/1.22

recipes/hdf5/all/conandata.yml, trassir/win32-vc16/conanfile.txt
Specify library name and version:  **gflags/2.2.2**; **glog/0.4.0**; **hdf5/1.10.6**
=> T13189: conan packages - gflags/2.2.2; glog/0.4.0; hdf5/1.10.6

recipes/lmdb/all/CMakeLists.txt, recipes/lmdb/all/conandata.yml, recipes/lmdb/all/conanfile.py, recipes/lmdb/config.yml, trassir/win32-vc16/conanfile.txt
Specify library name and version:  **lmdb/0.9.28**
=> T14033: conan package - lmdb/0.9.28

recipes/sip/4.19.3/conanfile.py, trassir/win32-vc16/conanfile.txt
=> T13176: add libraries to vc16, that were lost in fd9297b6e33d ( #270 )

trassir/win32-vc120/conanfile-qt5.txt, trassir/win32-vc142/conanfile.txt
=> T12918: add curl to conan

trassir/win32-vc142/conanfile.txt
Specify library name and version:  **libpq/11.5**
=> T14039: add libpq to conan

trassir/win32-vc142/conanfile.txt
=> T12982: add jansson/2.12 to conan(vc142)

recipes/hidapi/all/FORKED-FROM.TXT, recipes/hidapi/all/conandata.yml, recipes/hidapi/all/conanfile.py, recipes/hidapi/all/test_package/CMakeLists.txt, recipes/hidapi/all/test_package/conanfile.py, recipes/hidapi/all/test_package/test_package.c, recipes/hidapi/config.yml, trassir/win32-vc142/conanfile.txt
Specify library name and version:  **hidapi/0.10.1**
=> T12981: add hidapi to conan

recipes/dlib/all/conandata.yml, recipes/dlib/all/conanfile.py, recipes/dlib/config.yml, trassir/win32-vc142/conanfile.txt
Specify library name and version:  **dlib/19.4**
=> T12959: add dlib to conan

recipes/qt/5.14.1.dssl1/LICENSE.md, recipes/qt/5.14.1.dssl1/README.md, recipes/qt/5.14.1.dssl1/conandata.yml, recipes/qt/5.14.1.dssl1/conanfile.py, recipes/qt/5.14.1.dssl1/forked-from.txt, recipes/qt/5.14.1.dssl1/patches/3f9c9db.diff, recipes/qt/5.14.1.dssl1/patches/3f9c9db_.diff, recipes/qt/5.14.1.dssl1/patches/a9cc8aa.diff, recipes/qt/5.14.1.dssl1/patches/aa2a39dea5.diff, recipes/qt/5.14.1.dssl1/patches/fbde9c7.diff, recipes/qt/5.14.1.dssl1/qtmodules.conf, recipes/qt/5.14.1.dssl1/test_package/CMakeLists.txt, recipes/qt/5.14.1.dssl1/test_package/conanfile.py, recipes/qt/5.14.1.dssl1/test_package/greeter.h, recipes/qt/5.14.1.dssl1/test_package/meson.build, recipes/qt/5.14.1.dssl1/test_package/test_package.cpp, recipes/qt/5.14.1.dssl1/test_package/test_package.pro, recipes/qt/config.yml, trassir/win32-vc142/conanfile.txt
Specify library name and version:  **qt/5.14.1.dssl1**
=> T11046: add qt5 to conan

recipes/pkgconf/all/conandata.yml, recipes/pkgconf/all/conanfile.py, recipes/pkgconf/all/forked-from.txt, recipes/pkgconf/all/patches/1.7.3-0001-meson-use-declare-dependencies.patch, recipes/pkgconf/all/patches/1.7.3-0002-clang-12-strndup-not-in-string-h.patch, recipes/pkgconf/all/patches/1.7.3-0003-meson-use-library.patch, recipes/pkgconf/all/patches/1.7.3-0004-PKG_CONF_PATH-allow-colon+semicolon-separator.patch, recipes/pkgconf/all/patches/1.7.4-0001-clang-12-strndup-not-in-string-h.patch, recipes/pkgconf/all/patches/1.7.4-0002-fix-static-link.patch, recipes/pkgconf/all/patches/1.7.4-0003-PKG_CONF_PATH-allow-colon+semicolon-separator.patch, recipes/pkgconf/all/test_package/CMakeLists.txt, recipes/pkgconf/all/test_package/conanfile.py, recipes/pkgconf/all/test_package/configure.ac, recipes/pkgconf/all/test_package/libexample1.pc, recipes/pkgconf/all/test_package/test_package.c, recipes/pkgconf/config.yml
=> T12424: add pkgconf for webkit

recipes/m4/all/conanfile.py, recipes/m4/all/forked-from.txt, recipes/msys2/all/conandata.yml, recipes/msys2/all/conanfile.py, recipes/msys2/all/forked-from.txt, recipes/msys2/config.yml, recipes/ruby/2.3.7/conanfile.py, recipes/ruby/2.3.7/forked-from.txt
=> T12424: add/update m4, msys2, ruby for webkit

recipes/gperf/all/conanfile.py
=> T12424: update gperf for webkit

recipes/icu/all/conanfile.py, recipes/icu/all/patches/win_debug_delete_suffix.patch, recipes/libiconv/all/conandata.yml, recipes/libiconv/all/patches/win_build_0001.patch, recipes/libiconv/config.yml, trassir/lnvr-gcc8/conanfile.txt
=> T12424: update icu and libiconv for webkit

recipes/autoconf/all/conandata.yml, recipes/autoconf/all/conanfile.py, recipes/autoconf/all/forked-from.txt, recipes/autoconf/all/patches/2.71-0001-autom4te-relocatable.patch, recipes/autoconf/all/patches/2.71-0002-no-perl-path-in-shebang.patch, recipes/autoconf/all/patches/2.71-0003-uppercase-autom4te_perllibdir.patch, recipes/autoconf/all/patches/2.71-0004-no-embedded-m4-paths.patch, recipes/autoconf/all/patches/2.71-0005-disable-man-regeneration.patch, recipes/autoconf/all/patches/2.71-0006-autoconf-no-embedded-trailer_m4-path.patch, recipes/autoconf/all/test_package/conanfile.py, recipes/autoconf/config.yml, recipes/automake/all/conandata.yml, recipes/automake/all/conanfile.py, recipes/automake/all/forked-from.txt, recipes/automake/all/patches/0001-help2man-no-discard-stderr-0.16.2.patch, recipes/automake/all/patches/0001-help2man-no-discard-stderr-0.16.3.patch, recipes/automake/all/patches/0002-no-perl-path-in-shebang-0.16.2.patch, recipes/automake/all/patches/0002-no-perl-path-in-shebang-0.16.3.patch, recipes/automake/all/patches/0003-remove-embedded-datadirs-introduce-automake-conan-includes-0.16.1.patch, recipes/automake/all/patches/0003-remove-embedded-datadirs-introduce-automake-conan-includes-0.16.2.patch, recipes/automake/all/patches/0003-remove-embedded-datadirs-introduce-automake-conan-includes-0.16.3.patch, recipes/automake/all/patches/0004-introduce-automake_perllibdir-0.16.2.patch, recipes/automake/all/patches/0004-introduce-automake_perllibdir-0.16.3.patch, recipes/automake/all/test_package/conanfile.py, recipes/automake/all/test_package/configure.ac, recipes/automake/all/test_package/extra.m4, recipes/automake/config.yml
=> T12424: add update autoconf and automake for webkit

recipes/qtwebkit/5.212.0-alpha4.dssl1/conanfile.py, recipes/qtwebkit/5.212.0-alpha4.dssl1/patches/OptionsQt.patch, recipes/qtwebkit/5.212.0-alpha4.dssl1/patches/clang-11-jsc.patch, recipes/qtwebkit/5.212.0-alpha4.dssl1/patches/cmake_version.patch, trassir/lnvr-gcc8/conanfile.txt, trassir/win32-vc142/conanfile.txt
=> T12424: add webkit

recipes/signalr-qt/all/conandata.yml, recipes/signalr-qt/all/conanfile.py, recipes/signalr-qt/all/patches/fix_build_deps.patch, recipes/signalr-qt/config.yml, trassir/lnvr-gcc8/conanfile.txt, trassir/win32-vc142/conanfile.txt
=> T14191: add signalr-qt to conan

builder/conan_tools.py
e.g. version = "1.3.5"
old paths:
['1', '3', '5']
['1', '3', 'x']
['1', 'x']
['all']
new paths:
['1', '3', '5']
['1', '3', 'x']
['1', '3']
['1', 'x', 'x']
['1', 'x']
['1']
['all']
=> add more paths for finders

recipes/libjpeg-turbo/all/CMakeLists.txt, recipes/libjpeg-turbo/all/conandata.yml, recipes/libjpeg-turbo/all/conanfile.py, recipes/libjpeg-turbo/all/forked-from.txt, recipes/libjpeg-turbo/all/test_package/CMakeLists.txt, recipes/libjpeg-turbo/all/test_package/conanfile.py, recipes/libjpeg-turbo/config.yml, trassir/lnvr-gcc8/conanfile.txt, trassir/win32-vc142/conanfile.txt
=> T16399: add components in libjpeg-turbo recipe

recipes/libpq/all/conandata.yml, recipes/libpq/all/conanfile.py, recipes/libpq/all/forked-from.txt, recipes/libpq/all/patches/9.6.19/001-Use-return-instead-of-exit-in-configure.patch, recipes/libpq/all/test_package/CMakeLists.txt, recipes/libpq/config.yml, recipes/openblas/all/forked-from.txt, trassir/lnvr-gcc8/conanfile.txt, trassir/win32-vc142/conanfile.txt
=> T16399: add components in libpq recipe

recipes/openblas/all/conandata.yml, recipes/openblas/all/conanfile.py, recipes/openblas/config.yml, trassir/win32-vc142/conanfile.txt
=> T16399: add components in openblas recipe

recipes/openh264/all/conanfile.py, trassir/lnvr-gcc8/conanfile.txt, trassir/win32-vc142/conanfile.txt
=> update openh264 recipe

recipes/signalr-qt/all/conanfile.py, recipes/signalr-qt/config.yml, trassir/lnvr-gcc8/conanfile.txt, trassir/win32-vc142/conanfile.txt
=> fix signalr-qt conanfile for find_cmake_package

trassir/win32-vc120/conanfile-qt5.txt, trassir/win32-vc120/conanfile.txt, trassir/win32-vc142/conanfile.txt, trassir/win64-vc142/conanfile.txt
=> T17907: add possibility to build grabbers on vc142

recipes/signalr-qt/all/conanfile.py, recipes/signalr-qt/all/patches/switch_to_dll_target.patch, trassir/lnvr-gcc8/conanfile.txt, trassir/win32-vc142/conanfile.txt, trassir/win64-vc142/conanfile.txt
=> T18806: Build SignalR library x64

trassir/win32-vc120/conanfile-qt5.txt, trassir/win32-vc120/conanfile.txt, trassir/win32-vc142/conanfile.txt, trassir/win64-vc142/conanfile.txt
forgot to merge this PR before, when diff was just created
original diff by `a.skorokhod`
=> T18819: remove intellivision

trassir/win64-vc142/conanfile.txt
forgot to merge this PR before, when diff was just created
original diff by me
=> T17738: use python x64 from conan

trassir/win64-vc142/conanfile.txt
=> T18803: facesdk lost files

trassir/win64-vc142/conanfile.txt
=> T19803: vanguard build Qt with translations

recipes/re2/all/CMakeLists.txt, recipes/re2/all/conandata.yml, recipes/re2/all/conanfile.py, recipes/re2/all/test_package/CMakeLists.txt, recipes/re2/all/test_package/conanfile.py, recipes/re2/all/test_package/test_package.cpp, recipes/re2/config.yml, trassir/lnvr-gcc8/conanfile.txt, trassir/win32-vc142/conanfile.txt, trassir/win64-vc142/conanfile.txt
Divide pull request:
https://github.com/trassir/conan-center-index/pull/398
=> Re2 - add new grpc version by portions

.jenkins/Dockerfile, .jenkins/Jenkinsfile
add jenkinsfile and dockerfile to build in jenkins with conan cache
=> add jenkinsfile and dockerfile

.github/workflows/lnvr-gcc8-release.yml
Первая часть исправления: https://github.com/trassir/conan-config/pull/18
=> T21779: disable system packages auto-installation

recipes/grpc/all/CMakeLists.txt, recipes/grpc/all/cmake/grpc_plugin_template.cmake.in, recipes/grpc/all/conandata.yml, recipes/grpc/all/conanfile.py, recipes/grpc/all/patches/v1.37.x/001-disable-cppstd-override.patch, recipes/grpc/all/patches/v1.38.x/001-disable-cppstd-override.patch, recipes/grpc/all/patches/v1.43.x/001-disable-cppstd-override.patch, recipes/grpc/all/patches/v1.44.x/001-disable-cppstd-override.patch, recipes/grpc/all/test_package/CMakeLists.txt, recipes/grpc/all/test_package/conanfile.py, recipes/grpc/all/test_package/helloworld.proto, recipes/grpc/all/test_package/test_package.cpp, recipes/grpc/config.yml, recipes/grpc/forked-from.txt, trassir/win32-vc142/conanfile.txt, trassir/win64-vc142/conanfile.txt
Only for Windows now. Will make a separate pull request for lnvr-gcc8 as we need to update etcd-grpc there as well.
=> T21152: update grpc

builder/conan_tools.py, trassir/win64-vc142/conanfile.txt
=> T21121: added face recognizer neural networks to win64 installer

recipes/postgresql/14.3.dssl1/conanfile.py, recipes/postgresql/14.3.dssl1/pgdump_mute_warnings.patch, trassir/win32-vc120/conanfile.txt, trassir/win64-vc142/conanfile.txt
T12775: Add pgdump/9.3.4@trassir/sdk120 package
=> T12775: Add pgdump/9.3.4
